
/* we use "para_name"+":" to search input parameters. */
/* NOTE: the "para_name" str should only appear once and cannot exist comments */
/* NOTE: the "para_name" str should only appear once and cannot exist comments */
/* NOTE: the "para_name" str should only appear once and cannot exist comments */

## Note: For systems with more than 2 planets, NBOD in nbody.h and the related source code must be changed accordingly
## NOTE: when fitting system with > 2 planets, change NBOD in nbody.h and related source code as well.

# parameters for planetaery system
#  in  sorlar mass
stellar_mass:       1.034
#
# integration time
t_start_yr:         0
t_total_yr:         4.2


# parameters for rkf78
# err in rkf78
err_ratio_rkf:      1e-4
# err in intgration
err_tolerance_intg: 1e-14



# setting the chain grid
N_iter:                 4000000
# NOTE: N-beta == n-ranks since we set n-ranks based on N beta, should at least be 2
N_beta:	                15

# Change 1:  
Beta_Values:            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

###################### number of parameters 
# test case, 15 parameters only
N_parm:     	        13  
#
# To random set the initial loci of all parameters (0) or not (1)
#      if not, then we should provide initial values (init loci) of all parameters 
Loci_init:              0
init_loci: 43.98, 19.2259, 0.0637, 89.98, 357.04, 224.9, 30.25, 39.0153, 0.068, 89.98, 0.17, 168.65, 253.39
# To random set the initial step sizes (proposals) of all parameters (0) or not (1)
#      if not, then we should provide initial step sizes of all parameters 
#
Step_init:              1
#      the initial step sizes (ratio of its distribution range) of all parameters 
# Change 2:  
init_step:           0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001
#      set the scaling of the proposals (init step) of different chains, Number = N beta
#         should turn off tuning to make it effective (as here we are manually tuning them)
# Change 3:  
scale_step_beta:       10.0, 5.0, 2.0, 1.0, 0.3, 0.1, 0.05, 0.02, 0.01, 0.003, 0.001, 0.0003, 0.0001, 0.00003, 0.00001



# set total N-iteration in a stack of batches
n_iter_a_stack:         5000
# number of iteration in a batch before judging should a swap be taken
n_iter_a_batch_base:    100
# random +/- range of n-iter-a-batch-base (must < n-iter-a-batch-base)
n_iter_a_batch_rand:    5
# Number of swaping propose will be tested
N_swap:                 6
# neighbor swap (0) or random swap (1)  
Swapmode:               1
#
# based on formula, save beta always swap, thus in the lastest version we don't swap the same beta chain. However, we can turn this on using SameBS (1). This control parameter can be useful when several parallel chains are set with fixed different proposal sizes (When Stepinit is 1, scalestepbeta is different,  TrueTuneNS is 0, and all chains are with beta = 1). We hope this strategy can be useful in TTV searching
SameBetaSwap:           1
#
# same beta copy: if two cains have the same beta, do copying (1) rather than swapping (0)
# not used at the moment 
SameBetaCopy:           0
# when to trigger samebc
SameBC_start:           1000000
SameBC_ratio:           100
#
# to force all chain become beta 1 chain
#AllBetaOne:             2000000

# tune and jump: use the best position found in tuning.
# NOTE: final interation in each stack should not swap
TuneAndJump:           1
# 
# tureTune 1: we tune and change.  0: tune used as search for best position only
TrueTuneNotSearch:     0
# for local convergence, we turn of swapping after restoreTrueTure, so be careful of the Number of Restore-True-Tune
RestoreTrueTune:     3000000 

# tuning the proposals 
# stop the tuning after N-stoptune
N_stoptune:             100000000000
# begin the tuning after N-begintune, set it >= Restore-True-Tune to speed up the code
N_begintune:            0      
#
# the N-iteration in tuning sigma_prop
n_iter_in_tune:         100
# the lower boundary ok accept rate  
ar_ok_lower:            0.22
# the upper boundary ok accept rate  
ar_ok_upper:            0.24
# the best ar
ar_best:                0.23
# the maximum diff for an acceptable ar
ar_accept_diff:         0.02
#
sigma_scale_half_ratio: 20
#

# set the range of sigma (check the set_sigma_range function in readin.c)
sigma_scale_min:        0.0000000001
sigma_scale_max:        0.01
# reset the sigma in the range if out of the min/max boundary
sigma_jumpin_ratio:     300

# save the chain starting from (burning)
i_save_begin:           0000

# initial random seed(rolling in mpi), set it <= 0 to use system time 
init_rand_seed:         21 
# ratio of the init gaussian_proposal_sigma to the allowed prior range
init_gp_ratio:          0.1



# about the datafile 
# set delimiter as "blank" if data is seperated as " "
# NOTE : the data file need be formated (same length of each number in the same column,
#        and separated with a single " ". Otherwise Nii-C cannot load it.  
Data_file:           real.txt
ndim_data:           4
Delimiter:           blank           


# file name of output
Fout_Len: 	    100
FoutPre: 	    chain
FoutSuf: 	    .dat
results_dir: 	    results 


########## Priors
# set prior range
# NOTE: make sure para*_max > para*_min !

# para0: planet mass in Earth mass
para0_max:  50 ### in units of earth-mass
para0_min:  10
#
# para1: period
para1_max:    19.5
para1_min:    19.0
#
# para2: ecc
para2_max:    0.1
para2_min:    0.01

# para3: inclination
para3_max: 91.8041749693
para3_min: 88.195825
#
#
# para4: 近点角
para4_max:  360
para4_min:  0
#
#
# para5: 均轮
para5_max:   360
para5_min:   0
#
#
# para6: planet mass in Earth mass
para6_max:  50
para6_min:  10
#
#
# para7: period
para7_max: 39.3
para7_min: 38.7
#
#
# para8: ecc
para8_max:  0.1
para8_min:  0.01
#
#
# para9: inclination
para9_max:  91.1293018856
para9_min:  88.8706981
#
#
# para10:  升交点赤经之差
para10_max:  20
para10_min:  0
#
#
# para11:  近点角
para11_max:  360
para11_min:  0
#
#
# para12: 均轮
para12_max:  360
para12_min:  0
#
#


#
##########################################
# parameters after this line are not used in TTV-Search mode.
# tune the temperature or not (default off)
Tune_Ladder:            0
N_stopTuneLadder:       3000000
# ladder tuning parameters
# scale parameters of ladder tuning
scale_tune_ladder:      0.2
# in case zero swap ar occurs
zero_stretch:           0.1



